-- Ordenação 
-- RECUPERAR TODAS AS PESSOAS EM ORDEM ALFABÉTICA
SELECT * FROM gym.person ORDER BY name;

-- SELECIONAR TODAS AS PESSOAS QUE NASCERAM DEPOIS DE 1992 EM ORDEM ALFABÉTICA
SELECT * FROM gym.person 
	WHERE birth_date >= '1992-01-01'
    ORDER BY 'name';


-- BETWEEN
-- SELECIONAR TODAS AS PESSOAS QUE NASCERAM ENTRE 1992 E 2001 EM ORDEM ALFABÉTICA
SELECT * FROM gym.person 
	WHERE birth_date BETWEEN '1992' AND '2001'
    ORDER BY 'name';

-- IN 
-- SELECIONAR TODAS AS PESSOAS QUE JÁ REALIZARAM ALGUM CHECK-IN
SELECT * FROM gym.person
	WHERE id IN (SELECT DISTINCT(person_id)
				FROM gym.check_in);

-- LIKE e LIKE BINARY
-- SELECIONAR TODAS AS PESSOAS QUE POSSUEM O MATCH EXATO DE NOME 'João' E COM A ÚLTIMA LETRA DO NOME SENDO 's' CASE SENSITIVE
SELECT * FROM gym.person
	WHERE name LIKE BINARY 'Daniel%';
	

-- FUNÇÕES DE AGREGAÇÃO 
-- AVG, MAX, MIN, SUM, COUNT 

-- VALOR TOTAL GASTO COM PAGAMENTOS DA ACADEMIA
SELECT payment FROM gym.payment;
-- GROUP BY
SELECT 'branch_cnpj',
		SUM('value')
FROM gym.payment
GROUP BY 'branch_cnpj';